# Generated by Django 4.2.2 on 2023-06-25 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ToDoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("erstellt_datum", models.DateField(default=datetime.date.today)),
                ("name", models.CharField(max_length=200)),
                ("fertig", models.BooleanField(default=False)),
            ],
        ),
    ]
